version: '2.1'

networks:
  monitor-net:
    driver: bridge

services:

  prometheus:
    image: prom/prometheus:v2.1.0
    volumes:
      - ./prometheus/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention=200h'
      - '--web.enable-lifecycle'
    restart: unless-stopped
    expose:
      - 9090
    ports:
      - "9090:9090"
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"

  pushgateway:
    image: prom/pushgateway
    restart: unless-stopped
    expose:
      - 9091
    ports:
      - "9091:9091"
    networks:
      - monitor-net


  influxdb:
    image: influxdb:1.8.10
    environment:
      - INFLUXDB_DB=mammut
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
   
    restart: unless-stopped
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
    networks:
      - monitor-net

  graphite:
    image: graphiteapp/graphite-statsd
    restart: unless-stopped
    ports:
      - "2003:2003"
      - "8080:8080"
    networks:
      - monitor-net      
    
    
  grafana:
    image: grafana/grafana
    container_name: grafana
    volumes:
      - ./grafana:/etc/grafana

    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped
    ports:
      - '3000:3000'
    networks:
      - monitor-net
    labels:
      org.label-schema.group: "monitoring"