apiVersion: 1

deleteDatasources:
  - name: prometheus


datasources:
  - name: prometheus
    type: prometheus
    url: http://prometheus:9090
    uid: prometheus

  - name: InfluxDB
    type: influxdb
    uid: influxdb
    access: proxy
    database: mammut
    user: admin
    password: admin
    url: http://influxdb:8086
    isDefault: true
    editable: true
    jsonData:    
      httpMode: GET

  - name: Graphite
    type: graphite
    uid: graphite
    access: proxy
    url: http://graphite:80
    jsonData:
      graphiteVersion: '1.1'        
